install.packages("shiny")
install.packages("msaR")
install.packages("ape")
install.packages("phangorn")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("remotes")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
library(BiocManager)
BiocManager::install("ggtree", version = "3.8")
