install.packages("shiny")
install.packages("phangorn")
install.packages("msaR")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ape")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("ggtree", version = "3.8")
